logging_params:
  save_dir: "logs"  # TensorBoard logs 디렉토리
#  name: "vae_model"

model_params:
  name: "BetaVAE"  # 모델 이름 (여기서는 'VAE'라고 가정)
  in_channels: 3
  latent_dim: 64

exp_params:
  manual_seed: 42
  optimizer_params:
    LR: 0.001
    weight_decay: 0.0001

data_params:
  batch_size: 2
  image_size: 64
  #root_dir: "/home/hkj/yolov10pj/yolov10_human/pytorch-Deep-SVDD/dataset"  # 데이터셋 경로
  data_path: "/home/hkj/yolov10pj/yolov10_human/pytorch-Deep-SVDD/dataset"
  train_transforms:
    - "Resize: (64, 64)"
    - "ToTensor"
    - "Normalize: (0.5,), (0.5,)"
  val_transforms:
    - "Resize: (64, 64)"
    - "ToTensor"
    - "Normalize: (0.5,), (0.5,)"

trainer_params:
  devices: [3]  # 사용할 GPU 설정, 또는 '0'으로 설정하면 GPU 0 사용
  max_epochs: 5
  accelerator: 'gpu'

